spring.data.mongodb.uri=mongodb+srv://karandedigvijay2_db_user:lJH77G6pJfbmb6VW@cluster0.xdjtphk.mongodb.net/githubclone?retryWrites=true&w=majority
cloudinary.cloud-name=dpzobapgz
cloudinary.api-key=543983541951447
cloudinary.api-secret=rhyT3RGWPsTsKmjASMgF9bT758o
jwt.secret=614E645267556B58703273357638792F423F4528482B4D6251655468576D5A71
server.port=8081

spring.data.redis.host=fluffy-change-amount-82332.db.redis.io
spring.data.redis.port=12249
spring.data.redis.username=default
spring.data.redis.password=Cwm0rGDLmAsz2VWeZSCKtp4dZn8EzCc5

spring.cache.type=redis