server.port=8081

spring.data.mongodb.uri=mongodb+srv://karandedigvijay2_db_user:tg6J13juizXZ4A8E@cluster0.xdjtphk.mongodb.net/githubclone?retryWrites=true&w=majority&tls=true
jwt.secret=mysupersecretkeymysupersecretkey123456

cloudinary.cloud-name=dpzobapgz
cloudinary.api-key=543983541951447
cloudinary.api-secret=rhyT3RGWPsTsKmjASMgF9bT758o